sudo: required
dist: trusty
language: cpp

# Setup build matrix
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - TRIGGER_DOWNSTREAM_BUILDS="yes"

  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - os: osx
    osx_image: xcode8
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - OSX_IMAGE_NAME="xcode_8_0"

  - os: osx
    osx_image: xcode8.1
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - OSX_IMAGE_NAME="xcode_8_1"

  - os: osx
    osx_image: xcode8.2
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - OSX_IMAGE_NAME="xcode_8_2"

  - os: osx
    osx_image: xcode8.3
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - OSX_IMAGE_NAME="xcode_8_3"

  - os: osx
    osx_image: xcode9
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - OSX_IMAGE_NAME="xcode_9_0"

before_install:
  # Set compilers
  - eval "${MATRIX_EVAL}"
  - echo $CC
  - echo $CXX
  
  # Get Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq --force-yes; fi

install:
  # Install Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt59base qt59svg qt59imageformats qt59tools; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt59/bin/qt59-env.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt5 --force; fi

# Build the Blind Crossword 3D app
script:
  - qmake Blind-Crossword-3D.pro
  - make CC=${CC} CXX=${CXX} LINK=${CXX}