sudo: required
dist: bionic
language: cpp

# Setup build matrix
matrix:
  - os: linux
    addons:
      apt:
        sources:
          - sourceline: "ppa:ubuntu-toolchain-r/test"
        packages:
          - g++-8
          - libstdc++-8-dev
          - libgl1-mesa-dev
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

  - os: osx
    osx_image: xcode11.3
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"
      - OSX_IMAGE_NAME="xcode_11_3"

before_install:
  # Set compilers
  - eval "${MATRIX_EVAL}"
  - echo $CC
  - echo $CXX
  
  # Work around intermittent failures on OSX
  # "Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)"
  # See https://stackoverflow.com/questions/46670305/how-to-change-ruby-version-for-homebrew-in-macos-in-travis-ci/46756693
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  
  # Get Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.14.1-bionic -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq --force-yes; fi

install:
  # Install Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt514base qt514svg qt514imageformats qt514speech qt514tools; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt514/bin/qt514-env.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt5 --force; fi

# Build the Blind Crossword 3D app
script:
  - qmake BlindCrossword3D.pro
  - make CC=${CC} CXX=${CXX} LINK=${CXX}
